#!/bin/sh

#    Copyright 2010 Chris Jang
#
#    This file is part of GATLAS.
#
#    GATLAS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    GATLAS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with GATLAS.  If not, see <http://www.gnu.org/licenses/>.

case $# in
  2) WAVEFRONT_SIZE=$1 ; MAX_MATRIX_SIZE=$2 ;;
  *) echo usage: $0 \<wavefront_size\> \<max_matrix_size\>
     exit 1
esac

N=$WAVEFRONT_SIZE

while [ $N -le $MAX_MATRIX_SIZE ]
do

    if [ `expr $N % 4` -eq 0 ]; then
    if [ `expr $N % 5` -eq 0 ]; then
    if [ `expr $N % $WAVEFRONT_SIZE` -eq 0 ]; then
        echo $N
    fi
    fi
    fi

    N=`expr $N + $WAVEFRONT_SIZE`

done
